language: python

python:
  - 2.7
  - 3.4

addons:
  postgresql: 9.3

services:
  - redis-server

install:
  - pip install --no-use-wheel -e .
  - pip install --allow-external cdecimal --no-use-wheel blueberrypy[all,speedups,dev]

before_script:
  - psql --command="CREATE ROLE tester PASSWORD 'tester' INHERIT LOGIN;" --username=postgres
  - createdb --encoding=UTF-8 --username=postgres --owner=tester test_blueberrypy
  - psql --command='CREATE EXTENSION postgis;' --dbname=test_blueberrypy --username=postgres
  - psql --command='CREATE EXTENSION postgis_topology;' --dbname=test_blueberrypy --username=postgres

script: tox

notifications:
  email: false
