language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.6-dev
  - nightly # == 3.7-dev
  - pypy
  - pypy3

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.6-dev
    - python: nightly
    - python: pypy
    - python: pypy3

cache: pip

addons:
  postgresql: 9.3

services:
  - redis-server

install:
  - pip install --allow-external cdecimal --no-use-wheel -e .[all,speedups,dev]
  - psql --command="CREATE ROLE tester PASSWORD 'tester' INHERIT LOGIN;" --username=postgres
  - createdb --encoding=UTF-8 --username=postgres --owner=tester test_blueberrypy
  - psql --command='CREATE EXTENSION postgis;' --dbname=test_blueberrypy --username=postgres
  - psql --command='CREATE EXTENSION postgis_topology;' --dbname=test_blueberrypy --username=postgres

before_script: export TOX_PY_VERSION="py$(echo $TRAVIS_PYTHON_VERSION | sed 's/\.//g')"

script: tox -e "${TOX_PY_VERSION}"

notifications:
  email: true
