language: python

python:
  - 2.7

addons:
  postgresql: 9.3

services:
  - redis-server

install:
  - pip install -e .
  - pip install --allow-external cdecimal blueberrypy[all,speedups,dev]

before_script:
  - createuser --pwprompt --username=postgres tester
  - createdb --encoding=UTF-8 --username=postgres --owner=tester test_blueberrypy
  # - psql -c 'GRANT ALL ON DATABASE test_blueberrypy TO tester;' test_blueberrypy postgres
  - psql --command='CREATE EXTENSION postgis;' --dbname=test_blueberrypy --username=postgres
  - psql --command='CREATE EXTENSION postgis_topology;' --dbname=test_blueberrypy --username=postgres

script: tox

notifications:
  email: false